List<Map<String, dynamic>> clothesList = [
  {
    'title': 'Porta',
    'product': '[KREAM Exclusive]',
    'content': 'Porta Metallic Numbe',
    'tagNumber': 3,
    'tags': const ['단독', '적립', '무료배송'],
    'discount': 15,
    'price': '115,600',
    'purchase': '구매가',
    'icon': true,
  },
  {
    'title': 'Asics',
    'product': 'Asics Gel-Kayano 14',
    'content': 'Black Glacier Grey',
    'tagNumber': 0,
    'tags': const [],
    'discount': null,
    'price': '198,000',
    'purchase': '즉시 구매가',
    'icon': false,
  },
  {
    'title': 'Monamhee',
    'product': 'Monamhee x 10 Corso',
    'content': 'Como Bianco Keyring',
    'tagNumber': 0,
    'tags': const [],
    'discount': null,
    'price': '68,000',
    'purchase': '즉시 구매가',
    'icon': false,
  },
  {
    'title': 'Jordan',
    'product': 'Jordan 3 x J Balvin',
    'content': 'Retro SP Sunset',
    'tagNumber': 0,
    'tags': const [],
    'discount': null,
    'price': '448,000',
    'purchase': '즉시 구매가',
    'icon': false,
  },
  {
    'title': 'Crocs',
    'product': 'Crocs x Levi\'s All',
    'content': 'Terrain Clog Bone Blue',
    'tagNumber': 0,
    'tags': const [],
    'discount': null,
    'price': '130,000',
    'purchase': '즉시 구매가',
    'icon': false,
  },
  {
    'title': 'Nike',
    'product': 'Nike x Albino & Preto',
    'content': 'SB Dunk Low Fossil',
    'tagNumber': 0,
    'tags': const [],
    'discount': null,
    'price': '220,000',
    'purchase': '즉시 구매가',
    'icon': false,
  },
];
